### ISSUE TITLE
Where and how to configure and launch ceph-ansible

### ISSUE THREAD

**Issue by dahorak** [Tendrl/usmqe-setup#43]
Now ceph-ansible is configured on qe_server, which expects to have qe_server in inventory file this way:
```
[qe_server]
localhost ansible_connection=local ansible_user=jenkins
```

This needs to be changed, and qe_server should not be listed in inventory file for particular cluster.

**Comment by dahorak** [comment]
@mbukatov, @mkudlej

**Comment by dahorak** [comment]
One possibility might be, to add qe_server dynamically to the inventory (http://docs.ansible.com/ansible/add_host_module.html)

**Comment by mbukatov** [comment]
As long as we are using `ceph-ansible.yml` playbook in a local way, I would rather add `hosts: localhost` and `connection: local` into the play directly, instead of referring to usmqe host which will be always localhost in this case anyway.

**Comment by mkudlej** [comment]
I think that solution mentioned by @mbukatov is OK.
