### ISSUE TITLE
add public key fails with ssl error

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/usmqe-setup#84]
When I run the tendrl_server playbook I get:
TASK [tendrl-repo : Add public key for master repo] ****************************
fatal: [tendrl]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for copr-be.cloud.fedoraproject.org:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

**Comment by dahorak** [comment]
Hi @japplewhite,
did you saw this error multiple times? For the first look, it seems to me like availability issue with the copr repo - so nothing, what we can fully fix on our side. But if it will repeat often, we should workaround it somehow (try the step multiple times, in case of failure or store the gpg key on some other place).

**Comment by mbukatov** [comment]
I'm closing this issue, this is a problem on copr side. Moreover there is [tendrl-ansible](https://github.com/Tendrl/tendrl-ansible) which should be used for installing Tendrl instead of usmqe-setup, unless one actually need to recreate our qe environment.
